version: '3'
services:
    utopia-front-end:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8083:80"
        labels:
            - "traefik.docker.network=Utopia-Net"
            - "traefik.enable=true"
            - "traefik.port=8080"
            - "traefik.http.routers.utopia_api.rule=Host(`utopia tech back end domain name`)"
            - "traefik.http.routers.utopia_api.tls=true"
            - "traefik.http.routers.utopia_api.tls.certresolver=le"
            - "traefik.http.routers.utopia_api.tls.domains[0].sans=utopia tech back end domain name"
            - "traefik.http.middlewares.secure-redirectscheme.redirectscheme.scheme=https"
            - "traefik.http.middlewares.secure-redirectscheme.redirectscheme.permanent=true"


    reverse-proxy:
        image: traefik:v2.0
        # Enables the web UI and tells Traefik to listen to docker
        command:
            - "--entryPoints.web.address=:80"
            - "--entryPoints.websecure.address=:443"
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--accesslog=true"
            - "--accesslog.filepath=/var/log/traefik-access.log"
            - "--accesslog.bufferingsize=1000"
            - "--log.filePath=/var/log/traefik.log"
            - "--certificatesResolvers.le.acme.email=companyemail@gmail.com"
            - "--certificatesResolvers.le.acme.storage=acme.json"
            - "--certificatesResolvers.le.acme.httpChallenge.entryPoint=web"

        ports:
            # The HTTP port
            - "80:80"
            - "443:443"
            # The Web UI (enabled by --api.insecure=true)
            - "8085:8080"
        volumes:
            # So that Traefik can listen to the Docker events
            - /var/run/docker.sock:/var/run/docker.sock
        restart: always


networks:
    default:
        external:
            name: Utopia-Net
